import Footer from "../components/Footer/Footer"
import Header from "../components/Header/Header"
import "./globals.sass"

export const metadata = {
  title: "Din Mægler",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <main>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  )
}